### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by paw-lu** [salsify/action-detect-and-tag-new-version#18]
Getting this warning on my GitHub actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: salsify/action-detect-and-tag-new-version.

---

Thanks for the great work here!

**Comment by dfreeman** [comment]
Thanks for the heads up, @paw-lu! Should be fixed as soon as the new v2.0.2 tag propagates to the marketplace.

**Comment by SamSverko** [comment]
Looks like the `2.0.2` version is in the [Marketplace](https://github.com/marketplace/actions/detect-and-tag-new-version)!
