### ISSUE TITLE
Update @actions/core package to v1.10.0 or greater to update SetOutput 

### ISSUE THREAD

**Issue by hotenov** [salsify/action-detect-and-tag-new-version#21]
Workflow started to warn:

> [Release](#)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Please, update @actions/core package in source code 😃

**Comment by dfreeman** [comment]
Should be fixed in the latest release in the marketplace!
